server:
  port: 8085

spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/iamsso_audit
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: iamsso_audit
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: public
    default-schema: iamsso_audit
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  consumer-group: audit-service
