server:
  port: 8083

spring:
  application:
    name: mfa-service
  datasource:
    url: jdbc:postgresql://localhost:5432/iamsso_mfa
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: iamsso_mfa
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: public
    default-schema: iamsso_mfa
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  totp:
    issuer: IAMSSO
  email-otp:
    ttl-seconds: 300
